name: todo_list_provider
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  asuka: ^2.2.1
  date_picker_timeline: ^1.2.6
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  flutter_slidable: ^3.1.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  path: ^1.9.0
  provider: ^6.1.2
  sqflite: ^2.3.3
  synchronized: ^3.3.0
  validatorless: ^1.2.3

dev_dependencies:
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: TodoListIcons
      fonts:
        - asset: assets/fonts/TodoListIcons.ttf
