name: todo_list_provider
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.3.3

dependencies:
  asuka: ^2.2.1
  date_picker_timeline: ^1.2.5
  firebase_auth: ^4.19.0
  firebase_core: ^2.28.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  flutter_slidable: ^3.1.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  intl: ^0.18.1
  path: ^1.9.0
  provider: ^6.1.2
  sqflite: ^2.3.3
  synchronized: ^3.1.0+1
  validatorless: ^1.2.3

dev_dependencies:
  # dart_code_metrics: ^5.7.6
  flutter_lints: ^3.0.2
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: TodoListIcons
      fonts:
        - asset: assets/fonts/TodoListIcons.ttf
