name: todo_list_provider
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  asuka: ^2.0.1
  date_picker_timeline: ^1.2.3
  firebase_auth: ^3.6.3
  firebase_core: ^1.20.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_overlay_loader: ^2.0.0
  flutter_signin_button: ^2.0.0
  flutter_slidable: ^2.0.0
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.1
  intl: ^0.17.0
  path: ^1.8.1
  provider: ^6.0.3
  sqflite: ^2.0.3+1
  synchronized: ^3.0.0+2
  validatorless: ^1.2.1

dev_dependencies:
  dart_code_metrics: ^4.17.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: TodoListIcons
      fonts:
        - asset: assets/fonts/TodoListIcons.ttf
