name: todo_list_provider
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.0.5

dependencies:
  asuka: ^2.1.0
  date_picker_timeline: ^1.2.5
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  flutter_slidable: ^3.0.0
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.4
  intl: ^0.18.0
  path: ^1.8.3
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  synchronized: ^3.1.0
  validatorless: ^1.2.3

dev_dependencies:
  dart_code_metrics: ^5.7.5
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: TodoListIcons
      fonts:
        - asset: assets/fonts/TodoListIcons.ttf
